-- Exercicios M2S06

--EX3
--Cria a tabela PROPRIETARIO com os campos: NOME, SOBRENOME e ENDERECO
CREATE TABLE PROPRIETARIO(
    NOME VARCHAR(40),
    SOBRENOME VARCHAR(100),
    ENDERECO VARCHAR(100)
);

--EX4
--Cria a tabela IMOVEL com os campos: TIPO_IMOVEL, VALOR, OBSERVACOES, DETALHES, ENDERECO
CREATE TABLE IMOVEL(
    TIPO_IMOVEL VARCHAR(6),
	VALOR FLOAT8,
	OBSERVACOES TEXT,
	DETALHES TEXT,
	ENDERECO VARCHAR(100)
);
	
--EX5
--Adiciona a coluna ID na tabela PROPRIETARIO
ALTER TABLE PROPRIETARIO ADD COLUMN ID SERIAL;
--define a coluna ID na tabela PROPRIETARIO, como chave primaria
ALTER TABLE PROPRIETARIO ADD CONSTRAINT ID_PROPRIETARIO_PK PRIMARY KEY(ID);

--EX6
--Adiciona a coluna ID na tabela IMOVEL
ALTER TABLE IMOVEL ADD COLUMN ID SERIAL;
--Define a coluna ID na tabela IMOVEL, como chave primaria
ALTER TABLE IMOVEL ADD CONSTRAINT ID_IMOVEL_PK PRIMARY KEY(ID);
	
--EX7
--Adiciona a coluna TELEFONE na tabela PROPRIETARIO
ALTER TABLE PROPRIETARIO ADD COLUMN TELEFONE VARCHAR(11);
--Adiciona a coluna ENDERECO_COMERCIAL na tabela PROPRIETARIO
ALTER TABLE PROPRIETARIO ADD COLUMN ENDERECO_COMERCIAL VARCHAR(100);

--EX8
--Exclui a coluna DETALHES da tabela IMOVEL
ALTER TABLE IMOVEL DROP COLUMN DETALHES;

--EX9
--Adiciona a coluna ID_PROPRIETARIO a tabela IMOVEL
ALTER TABLE IMOVEL ADD COLUMN ID_PROPRIETARIO INT;
--Define a coluna ID_PROPRIETARIO na tabela IMOVEL, como uma chave estrangeira da tabela PROPRIETARIO
ALTER TABLE IMOVEL ADD CONSTRAINT ID_PROPRIETARIO_FK FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID);

--EX10
--Exclui a tabela PROPRIETARIO
DROP TABLE PROPRIETARIO;
--Exclui a tabela IMOVEL
DROP TABLE IMOVEL;